version: "3.8"

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./results:/app/results
    environment:
      - CUDA_VISIBLE_DEVICES=0  # Change if needed for GPU support
    restart: always
